# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 91166b5c635be86d691c7835ae05b533bcf5509386f97fad3e52ddaf07563aa7575608579e63702e3b598cd9abb501855f226b1c9de9c5b8afa203c3703df804

test:
  secret_key_base: e8bdb0cee920cb4897e8eaccacad76333b3a8b54fb466993db1ce1dbf444d1c19033804de396af4cfeea51871d23800584411b2c8db44899e138554c68c4ba48

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
